In [1]:
import tensorflow as tf

In [8]:
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)
with tf.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(x, feed_dict={x: "sup", y:30, z:3.14})
    print(output)

sup


In [9]:
import numpy as np

In [12]:
A = np.matrix([[-0.5, 0.2, 0.1], 
          [0.7, -0.8, 0.2]])

In [13]:
B = np.matrix([0.2,0.5,0.6])

In [16]:
A*B.T + np.matrix([0.1,0.2]).T

matrix([[ 0.16],
        [ 0.06]])

In [17]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)

In [18]:
A

matrix([[-0.5,  0.2,  0.1],
        [ 0.7, -0.8,  0.2]])

In [19]:
B

matrix([[ 0.2,  0.5,  0.6]])

In [22]:
a = tf.Variable(A)

In [24]:
b = tf.Variable(B)

In [26]:
tf.matmul(A,B.T)

<tf.Tensor 'MatMul_1:0' shape=(2, 1) dtype=float64>

In [28]:
bias = tf.Variable(tf.zeros(5))

In [37]:
bias

<tf.Variable 'Variable_3:0' shape=(5,) dtype=float32_ref>